---
name: POE-Component-Client-SMTP
version: 0.12
author:
  - George Nistorica <ultadm@cpan.org>
abstract: Asynchronous mail sending with POE
license: perl
requires:
  Carp: 0
  Data::Dumper: 0
  POE: 0.26
  POE::Filter::Line: 0
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  Test::More: 0
provides:
  POE::Component::Client::SMTP:
    file: lib/POE/Component/Client/SMTP.pm
    version: 0.12
generated_by: Module::Build version 0.2611
