---
name: POE-Component-Client-SMTP
version: 0.21
author:
  - 'George Nistorica <ultadm@cpan.org>'
abstract: Asynchronous mail sending with POE
license: perl
resources:
  license: ~
requires:
  Carp: 0
  Data::Dumper: 0
  POE: 0.26
  POE::Filter::Line: 0
  POE::Filter::Stream: 0
  POE::Filter::Transparent::SMTP: 0.2
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  Symbol: 0
  Test::More: 0
  perl: 0
provides:
  POE::Component::Client::SMTP:
    file: lib/POE/Component/Client/SMTP.pm
    version: 0.21
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
