# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-SMTP
version:      0.04
version_from: lib/POE/Component/Client/SMTP.pm
installdirs:  site
requires:
    POE:                           0.25
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
